version: '3.8'

services:
  samples:
    image: startree/prometheus-sample-app:1.0.0
    ports:
     - 8080:8080
  origin:
    image: quay.io/prometheus/prometheus:v2.31.1
    command:
      - --storage.tsdb.retention.time=15d
      - --config.file=/etc/config/prometheus.yml
      - --storage.tsdb.path=/data
      - --web.enable-lifecycle
    user: "1000:1000"
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: origin/config
        target: /etc/config
      - type: bind
        source: origin/data
        target: /data
  target:
    image: quay.io/prometheus/prometheus:v2.34.0
    command:
      - --storage.tsdb.retention.time=15d
      - --config.file=/etc/config/prometheus.yml
      - --storage.tsdb.path=/data
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    user: "1000:1000"
    ports:
      - 9091:9090
    volumes:
      - type: bind
        source: target/config
        target: /etc/config
      - type: bind
        source: target/data
        target: /data

volumes:
  originData:
  targetData:
